# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc065373e88085de65c4889481399a25a6d053dba0b9442b05a0ec9bf9d1e388b1fdf954d305c12336fddf3f3cd1837099d1cf52e01d8eb322c400abf1d91752

test:
  secret_key_base: 8d0ec95e64fc96e7e424ffd4f9bc432f48265de115846c340a7a5b83fbb270c494cefc3f8390e3ec179d7d7786818374383fc7238179236450cf714b648d16c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
